baseURL: "https://reorx.github.io/hugo-PaperModX/"
title: PaperModX
paginate: 5
theme: PaperModX

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Theme PaperModX - https://github.com/reorx/hugo-PaperModX"
  author:
    - Reorx
  mainSections:
    - posts
    - pages
    - categories
  disableAnchoredHeadings: true
  images: ["cover.png"]
  DateFormat: "2006-01-02"
  useCustomAnalytics: false
  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  ShowWordCount: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  TocOpen: true
  TocSide: "right"
  EnableInstantClick: true
  EnableImageZoom: true

  commentSystems:
    disqus:
      shortname: davidcraddocknet
  defaultCommentSystems:
    disqus: true

  profileMode:
    enabled: false
    title: PaperModX
    imageUrl: "#"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: /archives/
      - name: Tags
        url: /tags/

  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35

  # assets:
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Tags
          url: /tags/
          weight: 1
        - name: Archive
          url: /archives/
          weight: 2
        - name: Search
          url: /search/
          weight: 5

outputs:
  home:
    - HTML
    - RSS
    - JSON

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: github
    lineNos: true
    noClasses: false

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
